version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  be:
    container_name: be_django
    build:
      context: .
      args:
        DJANGO_SETTINGS_MODULE: "orders.settings.production"
    command: /bin/bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=db_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=admin
